### ISSUE TITLE
How would I pass monostate a f64 NAN?

### ISSUE THREAD

**Issue by TheNeikos** [dtolnay/monostate#1]
My datatype requires that a field is always NAN. Since Rust does not support `NAN` as a symbol I would have to use `f64::NAN` or `0.0/0.0` (as defined in the stdlib). But neither are compatible with monostate right now, as far as I can tell.

Is there a way I could still achieve it?

**Comment by dtolnay** [comment]
There isn't a way to do it with this library &mdash; you'd need to write your own type with a suitable Deserialize impl that checks for NaN.
